parameters:
  module-generator.settings.path: "%kernel.root_dir%/cache/test/settings.yml"
  module-generator.content-dumper.class: "ModuleGenerator\ModuleGenerator\ContentDumper\ConsoleOutputContentDumper"
