imports:
  - { resource: services.yml }

parameters:
  secret: secret
  module-generator.settings.path: "%kernel.root_dir%/settings.yml"
  module-generator.content-dumper.class: "ModuleGenerator\ModuleGenerator\ContentDumper\FilesystemContentDumper"

framework:
  form:
    csrf_protection: true
  secret: "%secret%"
  csrf_protection: ~
  session:
    handler_id: ~
  templating:
    engines: ['twig']
