imports:
  - { resource: ../src/ModuleGenerator/Settings/Resources/Config/services.yml }
  - { resource: ../src/ModuleGenerator/Update/Resources/Config/services.yml }
  - { resource: ../src/ModuleGenerator/ContentDumper/Resources/Config/services.yml }
