imports:
  - { resource: console.yml }

services:
    module-generator.settings:
        class: ModuleGenerator\ModuleGenerator\Settings\Settings
        arguments:
            - '%module-generator.settings.path%'
