imports:
  - { resource: console.yml }

services:
    module-generator.settings:
        class: ModuleGenerator\ModuleGenerator\Settings\Settings
        arguments:
            - '%kernel.root_dir%/settings.yml'
